export const colourOptions = [
  {
    'color': '#00B8D9',
    'isFixed': true,
    'label': 'Ocean',
    'value': 'ocean'
  },
  {
    'color': '#0052CC',
    'disabled': true,
    'label': 'Blue',
    'value': 'blue'
  },
  {
    'color': '#5243AA',
    'label': 'Purple',
    'value': 'purple'
  },
  {
    'color': '#FF5630',
    'isFixed': true,
    'label': 'Red',
    'value': 'red'
  },
  {
    'color': '#FF8B00',
    'label': 'Orange',
    'value': 'orange'
  },
  {
    'color': '#FFC400',
    'label': 'Yellow',
    'value': 'yellow'
  },
  {
    'color': '#36B37E',
    'label': 'Green',
    'value': 'green'
  },
  {
    'color': '#00875A',
    'label': 'Forest',
    'value': 'forest'
  },
  {
    'color': '#253858',
    'label': 'Slate',
    'value': 'slate'
  },
  {
    'color': '#666666',
    'label': 'Silver',
    'value': 'silver'
  }
];

export const stateOptions = [
  {
    'label': 'Alabama',
    'value': 'AL'
  },
  {
    'label': 'Alaska',
    'value': 'AK'
  },
  {
    'label': 'American Samoa',
    'value': 'AS'
  },
  {
    'label': 'Arizona',
    'value': 'AZ'
  },
  {
    'label': 'Arkansas',
    'value': 'AR'
  },
  {
    'label': 'California',
    'value': 'CA'
  },
  {
    'label': 'Colorado',
    'value': 'CO'
  },
  {
    'label': 'Connecticut',
    'value': 'CT'
  },
  {
    'label': 'Delaware',
    'value': 'DE'
  },
  {
    'label': 'District Of Columbia',
    'value': 'DC'
  },
  {
    'label': 'Federated States Of Micronesia',
    'value': 'FM'
  },
  {
    'label': 'Florida',
    'value': 'FL'
  },
  {
    'label': 'Georgia',
    'value': 'GA'
  },
  {
    'label': 'Guam',
    'value': 'GU'
  },
  {
    'label': 'Hawaii',
    'value': 'HI'
  },
  {
    'label': 'Idaho',
    'value': 'ID'
  },
  {
    'label': 'Illinois',
    'value': 'IL'
  },
  {
    'label': 'Indiana',
    'value': 'IN'
  },
  {
    'label': 'Iowa',
    'value': 'IA'
  },
  {
    'label': 'Kansas',
    'value': 'KS'
  },
  {
    'label': 'Kentucky',
    'value': 'KY'
  },
  {
    'label': 'Louisiana',
    'value': 'LA'
  },
  {
    'label': 'Maine',
    'value': 'ME'
  },
  {
    'label': 'Marshall Islands',
    'value': 'MH'
  },
  {
    'label': 'Maryland',
    'value': 'MD'
  },
  {
    'label': 'Massachusetts',
    'value': 'MA'
  },
  {
    'label': 'Michigan',
    'value': 'MI'
  },
  {
    'label': 'Minnesota',
    'value': 'MN'
  },
  {
    'label': 'Mississippi',
    'value': 'MS'
  },
  {
    'label': 'Missouri',
    'value': 'MO'
  },
  {
    'label': 'Montana',
    'value': 'MT'
  },
  {
    'label': 'Nebraska',
    'value': 'NE'
  },
  {
    'label': 'Nevada',
    'value': 'NV'
  },
  {
    'label': 'New Hampshire',
    'value': 'NH'
  },
  {
    'label': 'New Jersey',
    'value': 'NJ'
  },
  {
    'label': 'New Mexico',
    'value': 'NM'
  },
  {
    'label': 'New York',
    'value': 'NY'
  },
  {
    'label': 'North Carolina',
    'value': 'NC'
  },
  {
    'label': 'North Dakota',
    'value': 'ND'
  },
  {
    'label': 'Northern Mariana Islands',
    'value': 'MP'
  },
  {
    'label': 'Ohio',
    'value': 'OH'
  },
  {
    'label': 'Oklahoma',
    'value': 'OK'
  },
  {
    'label': 'Oregon',
    'value': 'OR'
  },
  {
    'label': 'Palau',
    'value': 'PW'
  },
  {
    'label': 'Pennsylvania',
    'value': 'PA'
  },
  {
    'label': 'Puerto Rico',
    'value': 'PR'
  },
  {
    'label': 'Rhode Island',
    'value': 'RI'
  },
  {
    'label': 'South Carolina',
    'value': 'SC'
  },
  {
    'label': 'South Dakota',
    'value': 'SD'
  },
  {
    'label': 'Tennessee',
    'value': 'TN'
  },
  {
    'label': 'Texas',
    'value': 'TX'
  },
  {
    'label': 'Utah',
    'value': 'UT'
  },
  {
    'label': 'Vermont',
    'value': 'VT'
  },
  {
    'label': 'Virgin Islands',
    'value': 'VI'
  },
  {
    'label': 'Virginia',
    'value': 'VA'
  },
  {
    'label': 'Washington',
    'value': 'WA'
  },
  {
    'label': 'West Virginia',
    'value': 'WV'
  },
  {
    'label': 'Wisconsin',
    'value': 'WI'
  },
  {
    'label': 'Wyoming',
    'value': 'WY'
  }
];

export const countyCities = [
{'county': 'Adams', 'city': 'Benge', 'zipcode': '99105'},
{'county': 'Adams', 'city': 'Ritzville', 'zipcode': '99169'},
{'county': 'Adams', 'city': 'Lind', 'zipcode': '99341'},
{'county': 'Adams', 'city': 'Othello', 'zipcode': '99344'},
{'county': 'Adams', 'city': 'Washtucna', 'zipcode': '99371'},
{'county': 'Asotin', 'city': 'Anatone', 'zipcode': '99401'},
{'county': 'Asotin', 'city': 'Asotin', 'zipcode': '99402'},
{'county': 'Asotin', 'city': 'Clarkston', 'zipcode': '99403'},
{'county': 'Benton', 'city': 'Benton City', 'zipcode': '99320'},
{'county': 'Benton', 'city': 'Kennewick', 'zipcode': '99336'},
{'county': 'Benton', 'city': 'Kennewick', 'zipcode': '99337'},
{'county': 'Benton', 'city': 'Kennewick', 'zipcode': '99338'},
{'county': 'Benton', 'city': 'Paterson', 'zipcode': '99345'},
{'county': 'Benton', 'city': 'Plymouth', 'zipcode': '99346'},
{'county': 'Benton', 'city': 'Prosser', 'zipcode': '99350'},
{'county': 'Benton', 'city': 'Richland', 'zipcode': '99352'},
{'county': 'Benton', 'city': 'West Richland', 'zipcode': '99353'},
{'county': 'Benton', 'city': 'Richland', 'zipcode': '99354'},
{'county': 'Chelan', 'city': 'Wenatchee', 'zipcode': '98801'},
{'county': 'Chelan', 'city': 'Wenatchee', 'zipcode': '98807'},
{'county': 'Chelan', 'city': 'Ardenvoir', 'zipcode': '98811'},
{'county': 'Chelan', 'city': 'Cashmere', 'zipcode': '98815'},
{'county': 'Chelan', 'city': 'Chelan', 'zipcode': '98816'},
{'county': 'Chelan', 'city': 'Chelan Falls', 'zipcode': '98817'},
{'county': 'Chelan', 'city': 'Dryden', 'zipcode': '98821'},
{'county': 'Chelan', 'city': 'Entiat', 'zipcode': '98822'},
{'county': 'Chelan', 'city': 'Leavenworth', 'zipcode': '98826'},
{'county': 'Chelan', 'city': 'Malaga', 'zipcode': '98828'},
{'county': 'Chelan', 'city': 'Manson', 'zipcode': '98831'},
{'county': 'Chelan', 'city': 'Monitor', 'zipcode': '98836'},
{'county': 'Chelan', 'city': 'Peshastin', 'zipcode': '98847'},
{'county': 'Chelan', 'city': 'Stehekin', 'zipcode': '98852'},
{'county': 'Clallam', 'city': 'Beaver', 'zipcode': '98305'},
{'county': 'Clallam', 'city': 'Carlsborg', 'zipcode': '98324'},
{'county': 'Clallam', 'city': 'Clallam Bay', 'zipcode': '98326'},
{'county': 'Clallam', 'city': 'Forks', 'zipcode': '98331'},
{'county': 'Clallam', 'city': 'Joyce', 'zipcode': '98343'},
{'county': 'Clallam', 'city': 'La Push', 'zipcode': '98350'},
{'county': 'Clallam', 'city': 'Neah Bay', 'zipcode': '98357'},
{'county': 'Clallam', 'city': 'Port Angeles', 'zipcode': '98362'},
{'county': 'Clallam', 'city': 'Port Angeles', 'zipcode': '98363'},
{'county': 'Clallam', 'city': 'Sekiu', 'zipcode': '98381'},
{'county': 'Clallam', 'city': 'Sequim', 'zipcode': '98382'},
{'county': 'Clark', 'city': 'Amboy', 'zipcode': '98601'},
{'county': 'Clark', 'city': 'Battle Ground', 'zipcode': '98604'},
{'county': 'Clark', 'city': 'Brush Prairie', 'zipcode': '98606'},
{'county': 'Clark', 'city': 'Camas', 'zipcode': '98607'},
{'county': 'Clark', 'city': 'Heisson', 'zipcode': '98622'},
{'county': 'Clark', 'city': 'La Center', 'zipcode': '98629'},
{'county': 'Clark', 'city': 'Ridgefield', 'zipcode': '98642'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98660'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98661'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98662'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98663'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98664'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98665'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98666'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98667'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98668'},
{'county': 'Clark', 'city': 'Washougal', 'zipcode': '98671'},
{'county': 'Clark', 'city': 'Yacolt', 'zipcode': '98675'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98682'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98683'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98684'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98685'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98686'},
{'county': 'Clark', 'city': 'Vancouver', 'zipcode': '98687'},
{'county': 'Columbia', 'city': 'Dayton', 'zipcode': '99328'},
{'county': 'Columbia', 'city': 'Starbuck', 'zipcode': '99359'},
{'county': 'Cowlitz', 'city': 'Ryderwood', 'zipcode': '98581'},
{'county': 'Cowlitz', 'city': 'Ariel', 'zipcode': '98603'},
{'county': 'Cowlitz', 'city': 'Carrolls', 'zipcode': '98609'},
{'county': 'Cowlitz', 'city': 'Castle Rock', 'zipcode': '98611'},
{'county': 'Cowlitz', 'city': 'Cougar', 'zipcode': '98616'},
{'county': 'Cowlitz', 'city': 'Kalama', 'zipcode': '98625'},
{'county': 'Cowlitz', 'city': 'Kelso', 'zipcode': '98626'},
{'county': 'Cowlitz', 'city': 'Longview', 'zipcode': '98632'},
{'county': 'Cowlitz', 'city': 'Silverlake', 'zipcode': '98645'},
{'county': 'Cowlitz', 'city': 'Toutle', 'zipcode': '98649'},
{'county': 'Cowlitz', 'city': 'Woodland', 'zipcode': '98674'},
{'county': 'Douglas', 'city': 'East Wenatchee', 'zipcode': '98802'},
{'county': 'Douglas', 'city': 'Bridgeport', 'zipcode': '98813'},
{'county': 'Douglas', 'city': 'Mansfield', 'zipcode': '98830'},
{'county': 'Douglas', 'city': 'Orondo', 'zipcode': '98843'},
{'county': 'Douglas', 'city': 'Palisades', 'zipcode': '98845'},
{'county': 'Douglas', 'city': 'Rock Island', 'zipcode': '98850'},
{'county': 'Douglas', 'city': 'Waterville', 'zipcode': '98858'},
{'county': 'Ferry', 'city': 'Boyds', 'zipcode': '99107'},
{'county': 'Ferry', 'city': 'Curlew', 'zipcode': '99118'},
{'county': 'Ferry', 'city': 'Danville', 'zipcode': '99121'},
{'county': 'Ferry', 'city': 'Inchelium', 'zipcode': '99138'},
{'county': 'Ferry', 'city': 'Keller', 'zipcode': '99140'},
{'county': 'Ferry', 'city': 'Laurier', 'zipcode': '99146'},
{'county': 'Ferry', 'city': 'Malo', 'zipcode': '99150'},
{'county': 'Ferry', 'city': 'Orient', 'zipcode': '99160'},
{'county': 'Ferry', 'city': 'Republic', 'zipcode': '99166'},
{'county': 'Franklin', 'city': 'Pasco', 'zipcode': '99301'},
{'county': 'Franklin', 'city': 'Pasco', 'zipcode': '99302'},
{'county': 'Franklin', 'city': 'Connell', 'zipcode': '99326'},
{'county': 'Franklin', 'city': 'Eltopia', 'zipcode': '99330'},
{'county': 'Franklin', 'city': 'Kahlotus', 'zipcode': '99335'},
{'county': 'Franklin', 'city': 'Mesa', 'zipcode': '99343'},
{'county': 'Garfield', 'city': 'Pomeroy', 'zipcode': '99347'},
{'county': 'Grant', 'city': 'Ephrata', 'zipcode': '98823'},
{'county': 'Grant', 'city': 'George', 'zipcode': '98824'},
{'county': 'Grant', 'city': 'Marlin', 'zipcode': '98832'},
{'county': 'Grant', 'city': 'Moses Lake', 'zipcode': '98837'},
{'county': 'Grant', 'city': 'Quincy', 'zipcode': '98848'},
{'county': 'Grant', 'city': 'Soap Lake', 'zipcode': '98851'},
{'county': 'Grant', 'city': 'Stratford', 'zipcode': '98853'},
{'county': 'Grant', 'city': 'Warden', 'zipcode': '98857'},
{'county': 'Grant', 'city': 'Wilson Creek', 'zipcode': '98860'},
{'county': 'Grant', 'city': 'Coulee City', 'zipcode': '99115'},
{'county': 'Grant', 'city': 'Electric City', 'zipcode': '99123'},
{'county': 'Grant', 'city': 'Grand Coulee', 'zipcode': '99133'},
{'county': 'Grant', 'city': 'Hartline', 'zipcode': '99135'},
{'county': 'Grant', 'city': 'Beverly', 'zipcode': '99321'},
{'county': 'Grant', 'city': 'Mattawa', 'zipcode': '99349'},
{'county': 'Grant', 'city': 'Royal City', 'zipcode': '99357'},
{'county': 'Grays Harbor', 'city': 'Aberdeen', 'zipcode': '98520'},
{'county': 'Grays Harbor', 'city': 'Amanda Park', 'zipcode': '98526'},
{'county': 'Grays Harbor', 'city': 'Copalis Beach', 'zipcode': '98535'},
{'county': 'Grays Harbor', 'city': 'Copalis Crossing', 'zipcode': '98536'},
{'county': 'Grays Harbor', 'city': 'Cosmopolis', 'zipcode': '98537'},
{'county': 'Grays Harbor', 'city': 'Elma', 'zipcode': '98541'},
{'county': 'Grays Harbor', 'city': 'Grayland', 'zipcode': '98547'},
{'county': 'Grays Harbor', 'city': 'Hoquiam', 'zipcode': '98550'},
{'county': 'Grays Harbor', 'city': 'Humptulips', 'zipcode': '98552'},
{'county': 'Grays Harbor', 'city': 'Mccleary', 'zipcode': '98557'},
{'county': 'Grays Harbor', 'city': 'Malone', 'zipcode': '98559'},
{'county': 'Grays Harbor', 'city': 'Moclips', 'zipcode': '98562'},
{'county': 'Grays Harbor', 'city': 'Montesano', 'zipcode': '98563'},
{'county': 'Grays Harbor', 'city': 'Neilton', 'zipcode': '98566'},
{'county': 'Grays Harbor', 'city': 'Oakville', 'zipcode': '98568'},
{'county': 'Grays Harbor', 'city': 'Ocean Shores', 'zipcode': '98569'},
{'county': 'Grays Harbor', 'city': 'Pacific Beach', 'zipcode': '98571'},
{'county': 'Grays Harbor', 'city': 'Quinault', 'zipcode': '98575'},
{'county': 'Grays Harbor', 'city': 'Satsop', 'zipcode': '98583'},
{'county': 'Grays Harbor', 'city': 'Taholah', 'zipcode': '98587'},
{'county': 'Grays Harbor', 'city': 'Westport', 'zipcode': '98595'},
{'county': 'Island', 'city': 'Clinton', 'zipcode': '98236'},
{'county': 'Island', 'city': 'Coupeville', 'zipcode': '98239'},
{'county': 'Island', 'city': 'Freeland', 'zipcode': '98249'},
{'county': 'Island', 'city': 'Greenbank', 'zipcode': '98253'},
{'county': 'Island', 'city': 'Langley', 'zipcode': '98260'},
{'county': 'Island', 'city': 'Oak Harbor', 'zipcode': '98277'},
{'county': 'Island', 'city': 'Oak Harbor', 'zipcode': '98278'},
{'county': 'Island', 'city': 'Camano Island', 'zipcode': '98282'},
{'county': 'Jefferson', 'city': 'Brinnon', 'zipcode': '98320'},
{'county': 'Jefferson', 'city': 'Chimacum', 'zipcode': '98325'},
{'county': 'Jefferson', 'city': 'Port Hadlock', 'zipcode': '98339'},
{'county': 'Jefferson', 'city': 'Nordland', 'zipcode': '98358'},
{'county': 'Jefferson', 'city': 'Port Ludlow', 'zipcode': '98365'},
{'county': 'Jefferson', 'city': 'Port Townsend', 'zipcode': '98368'},
{'county': 'Jefferson', 'city': 'Quilcene', 'zipcode': '98376'},
{'county': 'King', 'city': 'Auburn', 'zipcode': '98001'},
{'county': 'King', 'city': 'Auburn', 'zipcode': '98002'},
{'county': 'King', 'city': 'Federal Way', 'zipcode': '98003'},
{'county': 'King', 'city': 'Bellevue', 'zipcode': '98004'},
{'county': 'King', 'city': 'Bellevue', 'zipcode': '98005'},
{'county': 'King', 'city': 'Bellevue', 'zipcode': '98006'},
{'county': 'King', 'city': 'Bellevue', 'zipcode': '98007'},
{'county': 'King', 'city': 'Bellevue', 'zipcode': '98008'},
{'county': 'King', 'city': 'Bellevue', 'zipcode': '98009'},
{'county': 'King', 'city': 'Black Diamond', 'zipcode': '98010'},
{'county': 'King', 'city': 'Bothell', 'zipcode': '98011'},
{'county': 'King', 'city': 'Burton', 'zipcode': '98013'},
{'county': 'King', 'city': 'Carnation', 'zipcode': '98014'},
{'county': 'King', 'city': 'Bellevue', 'zipcode': '98015'},
{'county': 'King', 'city': 'Duvall', 'zipcode': '98019'},
{'county': 'King', 'city': 'Enumclaw', 'zipcode': '98022'},
{'county': 'King', 'city': 'Federal Way', 'zipcode': '98023'},
{'county': 'King', 'city': 'Fall City', 'zipcode': '98024'},
{'county': 'King', 'city': 'Hobart', 'zipcode': '98025'},
{'county': 'King', 'city': 'Issaquah', 'zipcode': '98027'},
{'county': 'King', 'city': 'Kenmore', 'zipcode': '98028'},
{'county': 'King', 'city': 'Issaquah', 'zipcode': '98029'},
{'county': 'King', 'city': 'Kent', 'zipcode': '98030'},
{'county': 'King', 'city': 'Kent', 'zipcode': '98031'},
{'county': 'King', 'city': 'Kent', 'zipcode': '98032'},
{'county': 'King', 'city': 'Kirkland', 'zipcode': '98033'},
{'county': 'King', 'city': 'Kirkland', 'zipcode': '98034'},
{'county': 'King', 'city': 'Kent', 'zipcode': '98035'},
{'county': 'King', 'city': 'Maple Valley', 'zipcode': '98038'},
{'county': 'King', 'city': 'Medina', 'zipcode': '98039'},
{'county': 'King', 'city': 'Mercer Island', 'zipcode': '98040'},
{'county': 'King', 'city': 'Bothell', 'zipcode': '98041'},
{'county': 'King', 'city': 'Kent', 'zipcode': '98042'},
{'county': 'King', 'city': 'North Bend', 'zipcode': '98045'},
{'county': 'King', 'city': 'Pacific', 'zipcode': '98047'},
{'county': 'King', 'city': 'Preston', 'zipcode': '98050'},
{'county': 'King', 'city': 'Ravensdale', 'zipcode': '98051'},
{'county': 'King', 'city': 'Redmond', 'zipcode': '98052'},
{'county': 'King', 'city': 'Redmond', 'zipcode': '98053'},
{'county': 'King', 'city': 'Redondo', 'zipcode': '98054'},
{'county': 'King', 'city': 'Renton', 'zipcode': '98055'},
{'county': 'King', 'city': 'Renton', 'zipcode': '98056'},
{'county': 'King', 'city': 'Renton', 'zipcode': '98057'},
{'county': 'King', 'city': 'Renton', 'zipcode': '98058'},
{'county': 'King', 'city': 'Renton', 'zipcode': '98059'},
{'county': 'King', 'city': 'Seahurst', 'zipcode': '98062'},
{'county': 'King', 'city': 'Federal Way', 'zipcode': '98063'},
{'county': 'King', 'city': 'Kent', 'zipcode': '98064'},
{'county': 'King', 'city': 'Snoqualmie', 'zipcode': '98065'},
{'county': 'King', 'city': 'Vashon', 'zipcode': '98070'},
{'county': 'King', 'city': 'Auburn', 'zipcode': '98071'},
{'county': 'King', 'city': 'Woodinville', 'zipcode': '98072'},
{'county': 'King', 'city': 'Redmond', 'zipcode': '98073'},
{'county': 'King', 'city': 'Sammamish', 'zipcode': '98074'},
{'county': 'King', 'city': 'Sammamish', 'zipcode': '98075'},
{'county': 'King', 'city': 'Woodinville', 'zipcode': '98077'},
{'county': 'King', 'city': 'Kirkland', 'zipcode': '98083'},
{'county': 'King', 'city': 'Kent', 'zipcode': '98089'},
{'county': 'King', 'city': 'Auburn', 'zipcode': '98092'},
{'county': 'King', 'city': 'Federal Way', 'zipcode': '98093'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98101'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98102'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98103'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98104'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98105'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98106'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98107'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98108'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98109'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98111'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98112'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98113'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98114'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98115'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98116'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98117'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98118'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98119'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98121'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98122'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98124'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98125'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98126'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98127'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98129'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98131'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98132'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98133'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98134'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98136'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98138'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98139'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98141'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98144'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98145'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98146'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98148'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98151'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98154'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98155'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98158'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98160'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98161'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98164'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98165'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98166'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98168'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98170'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98171'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98174'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98175'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98177'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98178'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98181'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98184'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98185'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98188'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98190'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98191'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98194'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98195'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98198'},
{'county': 'King', 'city': 'Seattle', 'zipcode': '98199'},
{'county': 'King', 'city': 'Baring', 'zipcode': '98224'},
{'county': 'King', 'city': 'Skykomish', 'zipcode': '98288'},
{'county': 'Kitsap', 'city': 'Rollingbay', 'zipcode': '98061'},
{'county': 'Kitsap', 'city': 'Bainbridge Island', 'zipcode': '98110'},
{'county': 'Kitsap', 'city': 'Bremerton', 'zipcode': '98310'},
{'county': 'Kitsap', 'city': 'Bremerton', 'zipcode': '98311'},
{'county': 'Kitsap', 'city': 'Bremerton', 'zipcode': '98312'},
{'county': 'Kitsap', 'city': 'Bremerton', 'zipcode': '98314'},
{'county': 'Kitsap', 'city': 'Silverdale', 'zipcode': '98315'},
{'county': 'Kitsap', 'city': 'Burley', 'zipcode': '98322'},
{'county': 'Kitsap', 'city': 'Bremerton', 'zipcode': '98337'},
{'county': 'Kitsap', 'city': 'Hansville', 'zipcode': '98340'},
{'county': 'Kitsap', 'city': 'Indianola', 'zipcode': '98342'},
{'county': 'Kitsap', 'city': 'Keyport', 'zipcode': '98345'},
{'county': 'Kitsap', 'city': 'Kingston', 'zipcode': '98346'},
{'county': 'Kitsap', 'city': 'Manchester', 'zipcode': '98353'},
{'county': 'Kitsap', 'city': 'Olalla', 'zipcode': '98359'},
{'county': 'Kitsap', 'city': 'Port Gamble', 'zipcode': '98364'},
{'county': 'Kitsap', 'city': 'Port Orchard', 'zipcode': '98366'},
{'county': 'Kitsap', 'city': 'Port Orchard', 'zipcode': '98367'},
{'county': 'Kitsap', 'city': 'Poulsbo', 'zipcode': '98370'},
{'county': 'Kitsap', 'city': 'Retsil', 'zipcode': '98378'},
{'county': 'Kitsap', 'city': 'Seabeck', 'zipcode': '98380'},
{'county': 'Kitsap', 'city': 'Silverdale', 'zipcode': '98383'},
{'county': 'Kitsap', 'city': 'South Colby', 'zipcode': '98384'},
{'county': 'Kitsap', 'city': 'Southworth', 'zipcode': '98386'},
{'county': 'Kitsap', 'city': 'Suquamish', 'zipcode': '98392'},
{'county': 'Kitsap', 'city': 'Tracyton', 'zipcode': '98393'},
{'county': 'Kittitas', 'city': 'Snoqualmie Pass', 'zipcode': '98068'},
{'county': 'Kittitas', 'city': 'Cle Elum', 'zipcode': '98922'},
{'county': 'Kittitas', 'city': 'Easton', 'zipcode': '98925'},
{'county': 'Kittitas', 'city': 'Ellensburg', 'zipcode': '98926'},
{'county': 'Kittitas', 'city': 'Kittitas', 'zipcode': '98934'},
{'county': 'Kittitas', 'city': 'Ronald', 'zipcode': '98940'},
{'county': 'Kittitas', 'city': 'Roslyn', 'zipcode': '98941'},
{'county': 'Kittitas', 'city': 'South Cle Elum', 'zipcode': '98943'},
{'county': 'Kittitas', 'city': 'Thorp', 'zipcode': '98946'},
{'county': 'Kittitas', 'city': 'Vantage', 'zipcode': '98950'},
{'county': 'Klickitat', 'city': 'Appleton', 'zipcode': '98602'},
{'county': 'Klickitat', 'city': 'Bingen', 'zipcode': '98605'},
{'county': 'Klickitat', 'city': 'Centerville', 'zipcode': '98613'},
{'county': 'Klickitat', 'city': 'Dallesport', 'zipcode': '98617'},
{'county': 'Klickitat', 'city': 'Glenwood', 'zipcode': '98619'},
{'county': 'Klickitat', 'city': 'Goldendale', 'zipcode': '98620'},
{'county': 'Klickitat', 'city': 'Husum', 'zipcode': '98623'},
{'county': 'Klickitat', 'city': 'Klickitat', 'zipcode': '98628'},
{'county': 'Klickitat', 'city': 'Lyle', 'zipcode': '98635'},
{'county': 'Klickitat', 'city': 'Trout Lake', 'zipcode': '98650'},
{'county': 'Klickitat', 'city': 'Wahkiacus', 'zipcode': '98670'},
{'county': 'Klickitat', 'city': 'White Salmon', 'zipcode': '98672'},
{'county': 'Klickitat', 'city': 'Wishram', 'zipcode': '98673'},
{'county': 'Klickitat', 'city': 'Bickleton', 'zipcode': '99322'},
{'county': 'Klickitat', 'city': 'Roosevelt', 'zipcode': '99356'},
{'county': 'Lewis', 'city': 'Glenoma', 'zipcode': '98336'},
{'county': 'Lewis', 'city': 'Mineral', 'zipcode': '98355'},
{'county': 'Lewis', 'city': 'Morton', 'zipcode': '98356'},
{'county': 'Lewis', 'city': 'Packwood', 'zipcode': '98361'},
{'county': 'Lewis', 'city': 'Randle', 'zipcode': '98377'},
{'county': 'Lewis', 'city': 'Adna', 'zipcode': '98522'},
{'county': 'Lewis', 'city': 'Centralia', 'zipcode': '98531'},
{'county': 'Lewis', 'city': 'Chehalis', 'zipcode': '98532'},
{'county': 'Lewis', 'city': 'Cinebar', 'zipcode': '98533'},
{'county': 'Lewis', 'city': 'Curtis', 'zipcode': '98538'},
{'county': 'Lewis', 'city': 'Doty', 'zipcode': '98539'},
{'county': 'Lewis', 'city': 'Ethel', 'zipcode': '98542'},
{'county': 'Lewis', 'city': 'Galvin', 'zipcode': '98544'},
{'county': 'Lewis', 'city': 'Mossyrock', 'zipcode': '98564'},
{'county': 'Lewis', 'city': 'Napavine', 'zipcode': '98565'},
{'county': 'Lewis', 'city': 'Onalaska', 'zipcode': '98570'},
{'county': 'Lewis', 'city': 'Pe Ell', 'zipcode': '98572'},
{'county': 'Lewis', 'city': 'Salkum', 'zipcode': '98582'},
{'county': 'Lewis', 'city': 'Silver Creek', 'zipcode': '98585'},
{'county': 'Lewis', 'city': 'Toledo', 'zipcode': '98591'},
{'county': 'Lewis', 'city': 'Vader', 'zipcode': '98593'},
{'county': 'Lewis', 'city': 'Winlock', 'zipcode': '98596'},
{'county': 'Lincoln', 'city': 'Edwall', 'zipcode': '99008'},
{'county': 'Lincoln', 'city': 'Reardan', 'zipcode': '99029'},
{'county': 'Lincoln', 'city': 'Sprague', 'zipcode': '99032'},
{'county': 'Lincoln', 'city': 'Almira', 'zipcode': '99103'},
{'county': 'Lincoln', 'city': 'Creston', 'zipcode': '99117'},
{'county': 'Lincoln', 'city': 'Davenport', 'zipcode': '99122'},
{'county': 'Lincoln', 'city': 'Harrington', 'zipcode': '99134'},
{'county': 'Lincoln', 'city': 'Lamona', 'zipcode': '99144'},
{'county': 'Lincoln', 'city': 'Lincoln', 'zipcode': '99147'},
{'county': 'Lincoln', 'city': 'Mohler', 'zipcode': '99154'},
{'county': 'Lincoln', 'city': 'Odessa', 'zipcode': '99159'},
{'county': 'Lincoln', 'city': 'Wilbur', 'zipcode': '99185'},
{'county': 'Mason', 'city': 'Allyn', 'zipcode': '98524'},
{'county': 'Mason', 'city': 'Belfair', 'zipcode': '98528'},
{'county': 'Mason', 'city': 'Grapeview', 'zipcode': '98546'},
{'county': 'Mason', 'city': 'Hoodsport', 'zipcode': '98548'},
{'county': 'Mason', 'city': 'Lilliwaup', 'zipcode': '98555'},
{'county': 'Mason', 'city': 'Matlock', 'zipcode': '98560'},
{'county': 'Mason', 'city': 'Shelton', 'zipcode': '98584'},
{'county': 'Mason', 'city': 'Tahuya', 'zipcode': '98588'},
{'county': 'Mason', 'city': 'Union', 'zipcode': '98592'},
{'county': 'Okanogan', 'city': 'Brewster', 'zipcode': '98812'},
{'county': 'Okanogan', 'city': 'Carlton', 'zipcode': '98814'},
{'county': 'Okanogan', 'city': 'Conconully', 'zipcode': '98819'},
{'county': 'Okanogan', 'city': 'Loomis', 'zipcode': '98827'},
{'county': 'Okanogan', 'city': 'Malott', 'zipcode': '98829'},
{'county': 'Okanogan', 'city': 'Mazama', 'zipcode': '98833'},
{'county': 'Okanogan', 'city': 'Methow', 'zipcode': '98834'},
{'county': 'Okanogan', 'city': 'Okanogan', 'zipcode': '98840'},
{'county': 'Okanogan', 'city': 'Omak', 'zipcode': '98841'},
{'county': 'Okanogan', 'city': 'Oroville', 'zipcode': '98844'},
{'county': 'Okanogan', 'city': 'Pateros', 'zipcode': '98846'},
{'county': 'Okanogan', 'city': 'Riverside', 'zipcode': '98849'},
{'county': 'Okanogan', 'city': 'Tonasket', 'zipcode': '98855'},
{'county': 'Okanogan', 'city': 'Twisp', 'zipcode': '98856'},
{'county': 'Okanogan', 'city': 'Wauconda', 'zipcode': '98859'},
{'county': 'Okanogan', 'city': 'Winthrop', 'zipcode': '98862'},
{'county': 'Okanogan', 'city': 'Coulee Dam', 'zipcode': '99116'},
{'county': 'Okanogan', 'city': 'Elmer City', 'zipcode': '99124'},
{'county': 'Okanogan', 'city': 'Nespelem', 'zipcode': '99155'},
{'county': 'Pacific', 'city': 'Bay Center', 'zipcode': '98527'},
{'county': 'Pacific', 'city': 'Lebam', 'zipcode': '98554'},
{'county': 'Pacific', 'city': 'Menlo', 'zipcode': '98561'},
{'county': 'Pacific', 'city': 'Raymond', 'zipcode': '98577'},
{'county': 'Pacific', 'city': 'South Bend', 'zipcode': '98586'},
{'county': 'Pacific', 'city': 'Tokeland', 'zipcode': '98590'},
{'county': 'Pacific', 'city': 'Chinook', 'zipcode': '98614'},
{'county': 'Pacific', 'city': 'Ilwaco', 'zipcode': '98624'},
{'county': 'Pacific', 'city': 'Long Beach', 'zipcode': '98631'},
{'county': 'Pacific', 'city': 'Nahcotta', 'zipcode': '98637'},
{'county': 'Pacific', 'city': 'Naselle', 'zipcode': '98638'},
{'county': 'Pacific', 'city': 'Ocean Park', 'zipcode': '98640'},
{'county': 'Pacific', 'city': 'Oysterville', 'zipcode': '98641'},
{'county': 'Pacific', 'city': 'Seaview', 'zipcode': '98644'},
{'county': 'Pend Oreille', 'city': 'Cusick', 'zipcode': '99119'},
{'county': 'Pend Oreille', 'city': 'Ione', 'zipcode': '99139'},
{'county': 'Pend Oreille', 'city': 'Metaline', 'zipcode': '99152'},
{'county': 'Pend Oreille', 'city': 'Metaline Falls', 'zipcode': '99153'},
{'county': 'Pend Oreille', 'city': 'Newport', 'zipcode': '99156'},
{'county': 'Pend Oreille', 'city': 'Usk', 'zipcode': '99180'},
{'county': 'Pierce', 'city': 'Anderson Island', 'zipcode': '98303'},
{'county': 'Pierce', 'city': 'Ashford', 'zipcode': '98304'},
{'county': 'Pierce', 'city': 'Buckley', 'zipcode': '98321'},
{'county': 'Pierce', 'city': 'Carbonado', 'zipcode': '98323'},
{'county': 'Pierce', 'city': 'Dupont', 'zipcode': '98327'},
{'county': 'Pierce', 'city': 'Eatonville', 'zipcode': '98328'},
{'county': 'Pierce', 'city': 'Gig Harbor', 'zipcode': '98329'},
{'county': 'Pierce', 'city': 'Elbe', 'zipcode': '98330'},
{'county': 'Pierce', 'city': 'Gig Harbor', 'zipcode': '98332'},
{'county': 'Pierce', 'city': 'Fox Island', 'zipcode': '98333'},
{'county': 'Pierce', 'city': 'Gig Harbor', 'zipcode': '98335'},
{'county': 'Pierce', 'city': 'Graham', 'zipcode': '98338'},
{'county': 'Pierce', 'city': 'Kapowsin', 'zipcode': '98344'},
{'county': 'Pierce', 'city': 'La Grande', 'zipcode': '98348'},
{'county': 'Pierce', 'city': 'Lakebay', 'zipcode': '98349'},
{'county': 'Pierce', 'city': 'Longbranch', 'zipcode': '98351'},
{'county': 'Pierce', 'city': 'Sumner', 'zipcode': '98352'},
{'county': 'Pierce', 'city': 'Milton', 'zipcode': '98354'},
{'county': 'Pierce', 'city': 'Orting', 'zipcode': '98360'},
{'county': 'Pierce', 'city': 'Puyallup', 'zipcode': '98371'},
{'county': 'Pierce', 'city': 'Puyallup', 'zipcode': '98372'},
{'county': 'Pierce', 'city': 'Puyallup', 'zipcode': '98373'},
{'county': 'Pierce', 'city': 'Puyallup', 'zipcode': '98374'},
{'county': 'Pierce', 'city': 'Puyallup', 'zipcode': '98375'},
{'county': 'Pierce', 'city': 'South Prairie', 'zipcode': '98385'},
{'county': 'Pierce', 'city': 'Spanaway', 'zipcode': '98387'},
{'county': 'Pierce', 'city': 'Steilacoom', 'zipcode': '98388'},
{'county': 'Pierce', 'city': 'Sumner', 'zipcode': '98390'},
{'county': 'Pierce', 'city': 'Bonney Lake', 'zipcode': '98391'},
{'county': 'Pierce', 'city': 'Vaughn', 'zipcode': '98394'},
{'county': 'Pierce', 'city': 'Wauna', 'zipcode': '98395'},
{'county': 'Pierce', 'city': 'Wilkeson', 'zipcode': '98396'},
{'county': 'Pierce', 'city': 'Longmire', 'zipcode': '98397'},
{'county': 'Pierce', 'city': 'Paradise Inn', 'zipcode': '98398'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98401'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98402'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98403'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98404'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98405'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98406'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98407'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98408'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98409'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98411'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98412'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98413'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98415'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98416'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98417'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98418'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98419'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98421'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98422'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98424'},
{'county': 'Pierce', 'city': 'Camp Murray', 'zipcode': '98430'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98431'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98433'},
{'county': 'Pierce', 'city': 'Mcchord Afb', 'zipcode': '98438'},
{'county': 'Pierce', 'city': 'Lakewood', 'zipcode': '98439'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98442'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98443'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98444'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98445'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98446'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98447'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98448'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98450'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98455'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98460'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98464'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98465'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98466'},
{'county': 'Pierce', 'city': 'University Place', 'zipcode': '98467'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98471'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98477'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98481'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98490'},
{'county': 'Pierce', 'city': 'Lakewood', 'zipcode': '98492'},
{'county': 'Pierce', 'city': 'Tacoma', 'zipcode': '98493'},
{'county': 'Pierce', 'city': 'Lakewood', 'zipcode': '98496'},
{'county': 'Pierce', 'city': 'Lakewood', 'zipcode': '98497'},
{'county': 'Pierce', 'city': 'Lakewood', 'zipcode': '98498'},
{'county': 'Pierce', 'city': 'Lakewood', 'zipcode': '98499'},
{'county': 'Pierce', 'city': 'Mckenna', 'zipcode': '98558'},
{'county': 'Pierce', 'city': 'Roy', 'zipcode': '98580'},
{'county': 'San Juan', 'city': 'Blakely Island', 'zipcode': '98222'},
{'county': 'San Juan', 'city': 'Deer Harbor', 'zipcode': '98243'},
{'county': 'San Juan', 'city': 'Eastsound', 'zipcode': '98245'},
{'county': 'San Juan', 'city': 'Friday Harbor', 'zipcode': '98250'},
{'county': 'San Juan', 'city': 'Lopez Island', 'zipcode': '98261'},
{'county': 'San Juan', 'city': 'Olga', 'zipcode': '98279'},
{'county': 'San Juan', 'city': 'Orcas', 'zipcode': '98280'},
{'county': 'San Juan', 'city': 'Shaw Island', 'zipcode': '98286'},
{'county': 'San Juan', 'city': 'Waldron', 'zipcode': '98297'},
{'county': 'Skagit', 'city': 'Anacortes', 'zipcode': '98221'},
{'county': 'Skagit', 'city': 'Bow', 'zipcode': '98232'},
{'county': 'Skagit', 'city': 'Burlington', 'zipcode': '98233'},
{'county': 'Skagit', 'city': 'Clearlake', 'zipcode': '98235'},
{'county': 'Skagit', 'city': 'Concrete', 'zipcode': '98237'},
{'county': 'Skagit', 'city': 'Conway', 'zipcode': '98238'},
{'county': 'Skagit', 'city': 'Hamilton', 'zipcode': '98255'},
{'county': 'Skagit', 'city': 'La Conner', 'zipcode': '98257'},
{'county': 'Skagit', 'city': 'Lyman', 'zipcode': '98263'},
{'county': 'Skagit', 'city': 'Marblemount', 'zipcode': '98267'},
{'county': 'Skagit', 'city': 'Mount Vernon', 'zipcode': '98273'},
{'county': 'Skagit', 'city': 'Mount Vernon', 'zipcode': '98274'},
{'county': 'Skagit', 'city': 'Rockport', 'zipcode': '98283'},
{'county': 'Skagit', 'city': 'Sedro Woolley', 'zipcode': '98284'},
{'county': 'Skamania', 'city': 'Carson', 'zipcode': '98610'},
{'county': 'Skamania', 'city': 'North Bonneville', 'zipcode': '98639'},
{'county': 'Skamania', 'city': 'Stevenson', 'zipcode': '98648'},
{'county': 'Skamania', 'city': 'Underwood', 'zipcode': '98651'},
{'county': 'Snohomish', 'city': 'Bothell', 'zipcode': '98012'},
{'county': 'Snohomish', 'city': 'Edmonds', 'zipcode': '98020'},
{'county': 'Snohomish', 'city': 'Bothell', 'zipcode': '98021'},
{'county': 'Snohomish', 'city': 'Edmonds', 'zipcode': '98026'},
{'county': 'Snohomish', 'city': 'Lynnwood', 'zipcode': '98036'},
{'county': 'Snohomish', 'city': 'Lynnwood', 'zipcode': '98037'},
{'county': 'Snohomish', 'city': 'Mountlake Terrace', 'zipcode': '98043'},
{'county': 'Snohomish', 'city': 'Lynnwood', 'zipcode': '98046'},
{'county': 'Snohomish', 'city': 'Mill Creek', 'zipcode': '98082'},
{'county': 'Snohomish', 'city': 'Lynnwood', 'zipcode': '98087'},
{'county': 'Snohomish', 'city': 'Everett', 'zipcode': '98201'},
{'county': 'Snohomish', 'city': 'Everett', 'zipcode': '98203'},
{'county': 'Snohomish', 'city': 'Everett', 'zipcode': '98204'},
{'county': 'Snohomish', 'city': 'Everett', 'zipcode': '98205'},
{'county': 'Snohomish', 'city': 'Everett', 'zipcode': '98206'},
{'county': 'Snohomish', 'city': 'Everett', 'zipcode': '98207'},
{'county': 'Snohomish', 'city': 'Everett', 'zipcode': '98208'},
{'county': 'Snohomish', 'city': 'Everett', 'zipcode': '98213'},
{'county': 'Snohomish', 'city': 'Arlington', 'zipcode': '98223'},
{'county': 'Snohomish', 'city': 'Darrington', 'zipcode': '98241'},
{'county': 'Snohomish', 'city': 'Gold Bar', 'zipcode': '98251'},
{'county': 'Snohomish', 'city': 'Granite Falls', 'zipcode': '98252'},
{'county': 'Snohomish', 'city': 'Index', 'zipcode': '98256'},
{'county': 'Snohomish', 'city': 'Lake Stevens', 'zipcode': '98258'},
{'county': 'Snohomish', 'city': 'North Lakewood', 'zipcode': '98259'},
{'county': 'Snohomish', 'city': 'Marysville', 'zipcode': '98270'},
{'county': 'Snohomish', 'city': 'Marysville', 'zipcode': '98271'},
{'county': 'Snohomish', 'city': 'Monroe', 'zipcode': '98272'},
{'county': 'Snohomish', 'city': 'Mukilteo', 'zipcode': '98275'},
{'county': 'Snohomish', 'city': 'Silvana', 'zipcode': '98287'},
{'county': 'Snohomish', 'city': 'Snohomish', 'zipcode': '98290'},
{'county': 'Snohomish', 'city': 'Snohomish', 'zipcode': '98291'},
{'county': 'Snohomish', 'city': 'Stanwood', 'zipcode': '98292'},
{'county': 'Snohomish', 'city': 'Startup', 'zipcode': '98293'},
{'county': 'Snohomish', 'city': 'Sultan', 'zipcode': '98294'},
{'county': 'Snohomish', 'city': 'Snohomish', 'zipcode': '98296'},
{'county': 'Spokane', 'city': 'Airway Heights', 'zipcode': '99001'},
{'county': 'Spokane', 'city': 'Chattaroy', 'zipcode': '99003'},
{'county': 'Spokane', 'city': 'Cheney', 'zipcode': '99004'},
{'county': 'Spokane', 'city': 'Colbert', 'zipcode': '99005'},
{'county': 'Spokane', 'city': 'Deer Park', 'zipcode': '99006'},
{'county': 'Spokane', 'city': 'Elk', 'zipcode': '99009'},
{'county': 'Spokane', 'city': 'Fairchild Air Force Base', 'zipcode': '99011'},
{'county': 'Spokane', 'city': 'Fairfield', 'zipcode': '99012'},
{'county': 'Spokane', 'city': 'Four Lakes', 'zipcode': '99014'},
{'county': 'Spokane', 'city': 'Greenacres', 'zipcode': '99016'},
{'county': 'Spokane', 'city': 'Latah', 'zipcode': '99018'},
{'county': 'Spokane', 'city': 'Liberty Lake', 'zipcode': '99019'},
{'county': 'Spokane', 'city': 'Marshall', 'zipcode': '99020'},
{'county': 'Spokane', 'city': 'Mead', 'zipcode': '99021'},
{'county': 'Spokane', 'city': 'Medical Lake', 'zipcode': '99022'},
{'county': 'Spokane', 'city': 'Mica', 'zipcode': '99023'},
{'county': 'Spokane', 'city': 'Newman Lake', 'zipcode': '99025'},
{'county': 'Spokane', 'city': 'Nine Mile Falls', 'zipcode': '99026'},
{'county': 'Spokane', 'city': 'Otis Orchards', 'zipcode': '99027'},
{'county': 'Spokane', 'city': 'Rockford', 'zipcode': '99030'},
{'county': 'Spokane', 'city': 'Spangle', 'zipcode': '99031'},
{'county': 'Spokane', 'city': 'Valleyford', 'zipcode': '99036'},
{'county': 'Spokane', 'city': 'Veradale', 'zipcode': '99037'},
{'county': 'Spokane', 'city': 'Waverly', 'zipcode': '99039'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99201'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99202'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99203'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99204'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99205'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99206'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99207'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99208'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99209'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99210'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99211'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99212'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99213'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99214'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99215'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99216'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99217'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99218'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99219'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99220'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99223'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99224'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99228'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99251'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99252'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99256'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99258'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99260'},
{'county': 'Spokane', 'city': 'Spokane', 'zipcode': '99299'},
{'county': 'Stevens', 'city': 'Ford', 'zipcode': '99013'},
{'county': 'Stevens', 'city': 'Tumtum', 'zipcode': '99034'},
{'county': 'Stevens', 'city': 'Wellpinit', 'zipcode': '99040'},
{'county': 'Stevens', 'city': 'Addy', 'zipcode': '99101'},
{'county': 'Stevens', 'city': 'Chewelah', 'zipcode': '99109'},
{'county': 'Stevens', 'city': 'Clayton', 'zipcode': '99110'},
{'county': 'Stevens', 'city': 'Colville', 'zipcode': '99114'},
{'county': 'Stevens', 'city': 'Evans', 'zipcode': '99126'},
{'county': 'Stevens', 'city': 'Fruitland', 'zipcode': '99129'},
{'county': 'Stevens', 'city': 'Gifford', 'zipcode': '99131'},
{'county': 'Stevens', 'city': 'Hunters', 'zipcode': '99137'},
{'county': 'Stevens', 'city': 'Kettle Falls', 'zipcode': '99141'},
{'county': 'Stevens', 'city': 'Loon Lake', 'zipcode': '99148'},
{'county': 'Stevens', 'city': 'Marcus', 'zipcode': '99151'},
{'county': 'Stevens', 'city': 'Northport', 'zipcode': '99157'},
{'county': 'Stevens', 'city': 'Rice', 'zipcode': '99167'},
{'county': 'Stevens', 'city': 'Springdale', 'zipcode': '99173'},
{'county': 'Stevens', 'city': 'Valley', 'zipcode': '99181'},
{'county': 'Thurston', 'city': 'Olympia', 'zipcode': '98501'},
{'county': 'Thurston', 'city': 'Olympia', 'zipcode': '98502'},
{'county': 'Thurston', 'city': 'Lacey', 'zipcode': '98503'},
{'county': 'Thurston', 'city': 'Olympia', 'zipcode': '98504'},
{'county': 'Thurston', 'city': 'Olympia', 'zipcode': '98505'},
{'county': 'Thurston', 'city': 'Olympia', 'zipcode': '98506'},
{'county': 'Thurston', 'city': 'Olympia', 'zipcode': '98507'},
{'county': 'Thurston', 'city': 'Olympia', 'zipcode': '98508'},
{'county': 'Thurston', 'city': 'Lacey', 'zipcode': '98509'},
{'county': 'Thurston', 'city': 'Tumwater', 'zipcode': '98511'},
{'county': 'Thurston', 'city': 'Olympia', 'zipcode': '98512'},
{'county': 'Thurston', 'city': 'Olympia', 'zipcode': '98513'},
{'county': 'Thurston', 'city': 'Olympia', 'zipcode': '98516'},
{'county': 'Thurston', 'city': 'Bucoda', 'zipcode': '98530'},
{'county': 'Thurston', 'city': 'East Olympia', 'zipcode': '98540'},
{'county': 'Thurston', 'city': 'Littlerock', 'zipcode': '98556'},
{'county': 'Thurston', 'city': 'Rainier', 'zipcode': '98576'},
{'county': 'Thurston', 'city': 'Rochester', 'zipcode': '98579'},
{'county': 'Thurston', 'city': 'Tenino', 'zipcode': '98589'},
{'county': 'Thurston', 'city': 'Yelm', 'zipcode': '98597'},
{'county': 'Thurston', 'city': 'Olympia', 'zipcode': '98599'},
{'county': 'Wahkiakum', 'city': 'Cathlamet', 'zipcode': '98612'},
{'county': 'Wahkiakum', 'city': 'Grays River', 'zipcode': '98621'},
{'county': 'Wahkiakum', 'city': 'Rosburg', 'zipcode': '98643'},
{'county': 'Wahkiakum', 'city': 'Skamokawa', 'zipcode': '98647'},
{'county': 'Walla Walla', 'city': 'Burbank', 'zipcode': '99323'},
{'county': 'Walla Walla', 'city': 'College Place', 'zipcode': '99324'},
{'county': 'Walla Walla', 'city': 'Dixie', 'zipcode': '99329'},
{'county': 'Walla Walla', 'city': 'Prescott', 'zipcode': '99348'},
{'county': 'Walla Walla', 'city': 'Touchet', 'zipcode': '99360'},
{'county': 'Walla Walla', 'city': 'Waitsburg', 'zipcode': '99361'},
{'county': 'Walla Walla', 'city': 'Walla Walla', 'zipcode': '99362'},
{'county': 'Walla Walla', 'city': 'Wallula', 'zipcode': '99363'},
{'county': 'Whatcom', 'city': 'Acme', 'zipcode': '98220'},
{'county': 'Whatcom', 'city': 'Bellingham', 'zipcode': '98225'},
{'county': 'Whatcom', 'city': 'Bellingham', 'zipcode': '98226'},
{'county': 'Whatcom', 'city': 'Bellingham', 'zipcode': '98227'},
{'county': 'Whatcom', 'city': 'Bellingham', 'zipcode': '98228'},
{'county': 'Whatcom', 'city': 'Bellingham', 'zipcode': '98229'},
{'county': 'Whatcom', 'city': 'Blaine', 'zipcode': '98230'},
{'county': 'Whatcom', 'city': 'Blaine', 'zipcode': '98231'},
{'county': 'Whatcom', 'city': 'Custer', 'zipcode': '98240'},
{'county': 'Whatcom', 'city': 'Deming', 'zipcode': '98244'},
{'county': 'Whatcom', 'city': 'Everson', 'zipcode': '98247'},
{'county': 'Whatcom', 'city': 'Ferndale', 'zipcode': '98248'},
{'county': 'Whatcom', 'city': 'Lummi Island', 'zipcode': '98262'},
{'county': 'Whatcom', 'city': 'Lynden', 'zipcode': '98264'},
{'county': 'Whatcom', 'city': 'Maple Falls', 'zipcode': '98266'},
{'county': 'Whatcom', 'city': 'Nooksack', 'zipcode': '98276'},
{'county': 'Whatcom', 'city': 'Point Roberts', 'zipcode': '98281'},
{'county': 'Whatcom', 'city': 'Sumas', 'zipcode': '98295'},
{'county': 'Whitman', 'city': 'Lamont', 'zipcode': '99017'},
{'county': 'Whitman', 'city': 'Tekoa', 'zipcode': '99033'},
{'county': 'Whitman', 'city': 'Albion', 'zipcode': '99102'},
{'county': 'Whitman', 'city': 'Belmont', 'zipcode': '99104'},
{'county': 'Whitman', 'city': 'Colfax', 'zipcode': '99111'},
{'county': 'Whitman', 'city': 'Colton', 'zipcode': '99113'},
{'county': 'Whitman', 'city': 'Endicott', 'zipcode': '99125'},
{'county': 'Whitman', 'city': 'Farmington', 'zipcode': '99128'},
{'county': 'Whitman', 'city': 'Garfield', 'zipcode': '99130'},
{'county': 'Whitman', 'city': 'Hay', 'zipcode': '99136'},
{'county': 'Whitman', 'city': 'Lacrosse', 'zipcode': '99143'},
{'county': 'Whitman', 'city': 'Malden', 'zipcode': '99149'},
{'county': 'Whitman', 'city': 'Oakesdale', 'zipcode': '99158'},
{'county': 'Whitman', 'city': 'Palouse', 'zipcode': '99161'},
{'county': 'Whitman', 'city': 'Pullman', 'zipcode': '99163'},
{'county': 'Whitman', 'city': 'Pullman', 'zipcode': '99164'},
{'county': 'Whitman', 'city': 'Pullman', 'zipcode': '99165'},
{'county': 'Whitman', 'city': 'Rosalia', 'zipcode': '99170'},
{'county': 'Whitman', 'city': 'Saint John', 'zipcode': '99171'},
{'county': 'Whitman', 'city': 'Steptoe', 'zipcode': '99174'},
{'county': 'Whitman', 'city': 'Thornton', 'zipcode': '99176'},
{'county': 'Whitman', 'city': 'Uniontown', 'zipcode': '99179'},
{'county': 'Whitman', 'city': 'Hooper', 'zipcode': '99333'},
{'county': 'Yakima', 'city': 'Yakima', 'zipcode': '98901'},
{'county': 'Yakima', 'city': 'Yakima', 'zipcode': '98902'},
{'county': 'Yakima', 'city': 'Yakima', 'zipcode': '98903'},
{'county': 'Yakima', 'city': 'Yakima', 'zipcode': '98904'},
{'county': 'Yakima', 'city': 'Yakima', 'zipcode': '98907'},
{'county': 'Yakima', 'city': 'Yakima', 'zipcode': '98908'},
{'county': 'Yakima', 'city': 'Yakima', 'zipcode': '98909'},
{'county': 'Yakima', 'city': 'Brownstown', 'zipcode': '98920'},
{'county': 'Yakima', 'city': 'Buena', 'zipcode': '98921'},
{'county': 'Yakima', 'city': 'Cowiche', 'zipcode': '98923'},
{'county': 'Yakima', 'city': 'Goose Prairie', 'zipcode': '98929'},
{'county': 'Yakima', 'city': 'Grandview', 'zipcode': '98930'},
{'county': 'Yakima', 'city': 'Granger', 'zipcode': '98932'},
{'county': 'Yakima', 'city': 'Harrah', 'zipcode': '98933'},
{'county': 'Yakima', 'city': 'Mabton', 'zipcode': '98935'},
{'county': 'Yakima', 'city': 'Moxee', 'zipcode': '98936'},
{'county': 'Yakima', 'city': 'Naches', 'zipcode': '98937'},
{'county': 'Yakima', 'city': 'Outlook', 'zipcode': '98938'},
{'county': 'Yakima', 'city': 'Parker', 'zipcode': '98939'},
{'county': 'Yakima', 'city': 'Selah', 'zipcode': '98942'},
{'county': 'Yakima', 'city': 'Sunnyside', 'zipcode': '98944'},
{'county': 'Yakima', 'city': 'Tieton', 'zipcode': '98947'},
{'county': 'Yakima', 'city': 'Toppenish', 'zipcode': '98948'},
{'county': 'Yakima', 'city': 'Wapato', 'zipcode': '98951'},
{'county': 'Yakima', 'city': 'White Swan', 'zipcode': '98952'},
{'county': 'Yakima', 'city': 'Zillah', 'zipcode': '98953'}
]